name: 'Setup'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Typescript
      uses: ./.github/actions/Setup-Typescript
    - name: Set up Python
      uses: ./.github/actions/Setup-Python

