name: Checks-Python
on:
  workflow_call:
  workflow_dispatch:
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/Setup-Python

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/Setup-Python
      - name: Lint with black
        working-directory: ./python
        run: black --check ./src
      - name: Lint with pylint
        working-directory: ./python
        run: pylint --fail-under=8.0 ./src || exit 1
        # The || exit 1 ensures that if pylint fails, the job fails
  test:
    name: Test
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/Setup-Python
      - name: Test
        working-directory: ./python
        run: pytest
