name: Checks-Typescript
on:
  workflow_call:
  workflow_dispatch:
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [8]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/Setup-Typescript

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [8]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/Setup-Typescript
      - name: Lint & format code
        working-directory: ./typescript
        run: pnpm format & pnpm lint
  test:
    name: Test
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [8]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/Setup-Typescript
      - name: Test
        working-directory: ./typescript
        run: pnpm test:ci
  build:
    name: Build
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
        pnpm-version: [8]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/Setup-Typescript
      - name: Build
        working-directory: ./typescript
        run: pnpm build