name: Python Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      working-directory: ./python
      run: |
        python -m pip install --upgrade pip
        pip install black isort mypy pytest
        pip install -e .

    - name: Check formatting with black
      working-directory: ./python
      run: black --check ./src ./test

    - name: Sort imports with isort
      working-directory: ./python
      run: isort --check-only --diff ./src ./test

    - name: Type checking with mypy
      working-directory: ./python
      run: mypy --ignore-missing-imports ./src

    - name: Run tests with pytest
      working-directory: ./python
      run: pytest ./test -v