name: Python Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      working-directory: ./python
      run: |
        python -m pip install --upgrade pip
        pip install black isort mypy pytest build

    - name: Build and install package
      working-directory: ./python
      run: |
        python -m build
        pip install dist/*.whl

    - name: Test package imports
      working-directory: ./python
      run: |
        python -c "from balancer_maths import Vault; print('Package import successful!')"
        python -c "from balancer_maths import SwapInput, SwapKind; print('All exports available!')"

    - name: Test package in clean environment
      working-directory: ./python
      run: |
        python -m venv test_env
        source test_env/bin/activate
        pip install dist/*.whl
        python -c "from balancer_maths import Vault; print('Clean environment import successful!')"

    - name: Check formatting with black
      working-directory: ./python
      run: black --check ./src ./test

    - name: Sort imports with isort
      working-directory: ./python
      run: isort --check-only --diff ./src ./test

    - name: Type checking with mypy
      working-directory: ./python
      run: mypy --ignore-missing-imports ./src ./test

    - name: Run tests with pytest
      working-directory: ./python
      run: pytest ./test -v